dist: trusty
language: python

python:
  - "3.6.5"

env:
  - ACTION=test
  - ACTION=deploy
  - ACTION=integration
  - ACTION=codestyle

matrix:
  allow_failures:
    - env: ACTION=integration

services:
  - redis-server

cache:
  - apt
  - pip

addons:
  apt:
    packages:
    - libgdal-dev

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE=geotrek.settings.tests

install:
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal/" gdal==1.10.0
  - pip install -e . flake8 coverage
  - psql -c "create user geotrek superuser password 'geotrek'" -U postgres
  - psql -c "create database geotrekdb owner geotrek" -U postgres
  - ./manage.py collectstatic --noinput

script:
  - flake8 geotrek
  - find geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID
  - coverage run manage.py test geotrek

after_success:
  # Report coverage results to coveralls.io
  - ./bin/coverage report -m
  - pip install coveralls
  - coveralls
