dist: trusty
language: python

python:
  - "3.6.5"

env:
  - ACTION=test
  - ACTION=deploy
  - ACTION=integration
  - ACTION=codestyle

matrix:
  allow_failures:
    - env: ACTION=integration

services:
  - docker
  - redis-server

cache:
  - apt
  - pip

before_install:
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

after_success:
  # Report coverage results to coveralls.io
  - ./bin/coverage report -m
  - pip install coveralls
  - coveralls
