language: python

python:
  - "2.7"

cache:
  - apt

dist: trusty
sudo: required

env:
  - ACTION=test
  - ACTION=codestyle

before_install:
  - if [[ $ACTION != codestyle ]]; then sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose; fi
  - if [[ $ACTION != codestyle ]]; then sudo chmod +x /usr/local/bin/docker-compose; fi
  - if [[ $ACTION != codestyle ]]; then sudo service postgresql stop; fi
  - if [[ $ACTION != codestyle ]]; then docker volume create geotrek-admin_postgres; fi
  - if [[ $ACTION != codestyle ]]; then docker run --name geotrek-admin_postgres_1 -d juank/postgis:10-2.4 -v geotrek_postgres:/var/lib/postgresql/data -e POSTGRES_USER=geotrek_user -e POSTGRES_DB=geotrek_db -e POSTGRES_PASSWORD=geotrek_password; fi
  - if [[ $ACTION != codestyle ]]; then sleep 15; fi
  - if [[ $ACTION != codestyle ]]; then docker container stop geotrek-admin_postgres_1; fi

install:
  - if [[ $ACTION == codestyle ]]; then pip install flake8; fi
  - if [[ $ACTION != codestyle ]]; then docker-compose build; fi

script:
  - if [[ $ACTION == codestyle ]]; then flake8 --exclude "" --ignore=E501,F403,F405 geotrek/settings; fi
  - if [[ $ACTION == codestyle ]]; then flake8 geotrek; fi
  - if [[ $ACTION == codestyle ]]; then find geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID; fi
  - if [[ $ACTION == test ]]; then /app/venv/bin/coverage run docker-compose run web ./manage.py test geotrek --settings=geotrek.settings.tests; fi

after_success:
  # Report coverage results to coveralls.io
  - if [[ $ACTION == test ]]; then coverage report -m; fi
  - if [[ $ACTION == test ]]; then sudo pip install coveralls; fi
  - if [[ $ACTION == test ]]; then coveralls; fi
