dist: trusty
language: python

python:
  - "3.6.5"

env:
  - ACTION=test
  - ACTION=deploy
  - ACTION=integration
  - ACTION=codestyle

matrix:
  allow_failures:
    - env: ACTION=integration

services:
  - docker

before_install:
  - docker build .
  - docker
  - docker run -d -p 127.0.0.1:80:4567 bash -c "cd /home/django; bundle exec foreman start;"
  - docker ps -a
  - docker run bash -c "cd /home/django; bundle exec rake test"

script:
  - bundle exec rake test




