version: "3"
services:
  postgres:
    image: juank/postgis:10-2.4
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    hostname: geotrek-redis

  convertit:
     image: geotrekce/convertit
     working_dir: /opt/apps/convertit/
     command: /opt/apps/convertit/bin/pserve development.ini --reload

  screamshotter:
     image: geotrekce/screamshotter
     depends_on:
       - convertit
     command: /opt/apps/screamshotter/bin/python manage.py runserver 0.0.0.0:8001

  celery:
    image: geotrek
    build: .
    env_file:
      - docker.env
    depends_on:
      - postgres
      - redis
      - screamshotter
    working_dir: /app
    volumes:
      - ./geotrek:/app/geotrek
    command: /app/venv/bin/celery -A geotrek worker -l debug

  web:
     image: geotrek
     tty: true
     ports:
       - "8000:8000"
     env_file:
       - docker.env
     volumes:
       - static:/app/public/static
       - media:/app/public/media
       - cache:/app/private/cache
       - data_export:/app/private/data
       - ./conf/templates:/app/private/templates
       - ./conf/locale:/app/private/locale
       - ./conf/static:/app/private/static
       #- ./conf/geotrek.log:/app/private/log/geotrek.log
       - ./conf/custom.py:/app/geotrek/settings/custom.py
       - ./geotrek:/app/geotrek
     user: "1000"
     depends_on:
       - celery
     working_dir: /app
     command: ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
  cache:
  static:
  media:
  data_export:
