version: "3"
services:
  postgres:
    image: juank/postgis:10-2.4
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    hostname: geotrek-redis

  convertit:
     image: geotrekce/convertit
     working_dir: /opt/apps/convertit/
     command: /opt/apps/convertit/bin/pserve development.ini --reload

  screamshotter:
     image: geotrekce/screamshotter
     depends_on:
       - convertit

  celery:
    image: geotrek
    build: .
    env_file:
      - docker.env
    depends_on:
      - postgres
      - redis
      - screamshotter
    working_dir: /app/src
    volumes:
      - static:/app/src/public/static
      - media:/app/src/public/media
      - cache:/app/src/private/cache
      - data_export:/app/src/private/data
      - ./conf/templates:/app/src/private/templates
      - ./conf/bulkimport:/app/src/bulkimport
      - ./conf/locale:/app/src/private/locale
      - ./conf/static:/app/src/private/static
      - ./conf/log/geotrek:/app/src/private/log
      - ./conf/custom.py:/app/src/geotrek/settings/custom.py
      #- ./geotrek:/app/src/geotrek
    command: /app/venv/bin/celery -A geotrek worker -l debug

  web:
     image: geotrek
     tty: true
     ports:
       - "8000:8000"
     env_file:
       - docker.env
     volumes:
       - static:/app/src/public/static
       - media:/app/src/public/media
       - cache:/app/src/private/cache
       - data_export:/app/src/private/data
       - ./conf/templates:/app/src/private/templates
       - ./conf/bulkimport:/app/src/bulkimport
       - ./conf/locale:/app/src/private/locale
       - ./conf/static:/app/src/private/static
       - ./conf/log/geotrek:/app/src/private/log/
       - ./conf/custom.py:/app/src/geotrek/settings/custom.py
       #- ./geotrek:/app/src/geotrek
     #user: "1000"
     depends_on:
       - celery
     working_dir: /app/src
     command: ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
  cache:
  static:
  media:
  data_export:
