version: "3"
services:
  postgres:
    image: juank/postgis:10-2.4
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    hostname: geotrek-redis

  convertit:
     image: geotrekce/convertit
     working_dir: /opt/apps/convertit/
     command: /opt/apps/convertit/bin/pserve development.ini --reload

  screamshotter:
     image: geotrekce/screamshotter
     depends_on:
       - convertit

  celery:
    image: geotrek
    env_file:
      - docker.env
    build:
      context: .
      args:
        LOCAL_UID: ${LOCAL_USER_ID}
    depends_on:
      - postgres
      - redis
      - screamshotter
    volumes:
      - ./var:/app/src/var
      - ./var/custom.py:/app/src/geotrek/settings/custom.py
      - ./var/bulkimport:/app/src/bulkimport
      - ./geotrek:/app/src/geotrek
    working_dir: /app/src
    command: /app/venv/bin/celery -A geotrek worker -l debug

  web:
     image: geotrek
     tty: true
     hostname: ${DOMAIN_NAME}
     ports:
       - "8000:8000"
     env_file:
       - docker.env
     volumes:
       - ./var:/app/src/var
       - ./var/custom.py:/app/src/geotrek/settings/custom.py
       - ./var/bulkimport:/app/src/bulkimport
       - ./geotrek:/app/src/geotrek
     depends_on:
       - celery
     working_dir: /app/src
     command: ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
